# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'
# Uncomment this line if you're using Swift
# use_frameworks!

def common_JW
    pod 'JWPlayer-SDK', '~> 3.0'
end

target 'JWBestPracticeApps' do

    common_JW

end

target 'JWCasting' do

    common_JW
    pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWAirPlay' do

    common_JW

end

target 'JWRemotePlayer' do

    common_JW
    pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWRemoteController' do

end

target 'JWRemoteController Extension' do

end

target 'JWRemoteCastPlayer' do

    common_JW
    pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWRemoteCastController' do

end

target 'JWRemoteCastController Extension' do

end

target 'Voicer' do

    common_JW
    pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'VoicerExtension' do

end 

target 'JWFairPlayDrm' do

    common_JW
    pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWConviva' do

    pod 'ConvivaSDK'
    common_JW

end

workspace 'JWBestPracticeApps'

