//
//  OfflineDemoPlaylist.swift
//  JWPlayerKitDemoApp
//
//  Created by Stephen Seibert on 5/25/23.
//  Copyright © 2023 JW Player. All rights reserved.
//

import Foundation
import JWPlayerKit

// MARK: - Sample Playlist
// This is the base playlist we use for the demo. All media is online.
// Each item has a unique media id, set by this app for demo purposes.
// If you are using the JWP CDN, this media id is unique and automatically
// generated by JWP.

let samplePlaylist: [JWPlayerItem] = [
    // SINTEL
    try! JWPlayerItemBuilder()
        .mediaId("aaa123")
        .file(URL(string: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8")!)
        .title("HLS: Sintel")
        .posterImage(URL(string: "https://vdn.libreflix.org/covers/media/sintel/sintelthumb.jpg")!)
        .mediaTracks([
            try! JWCaptionTrackBuilder()
                .file(URL(string: "http://playertest.longtailvideo.com/caption-files/sintel-en.srt")!)
                .label("English")
                .build(),
            try! JWCaptionTrackBuilder()
                .file(URL(string: "http://playertest.longtailvideo.com/caption-files/sintel-sp.srt")!)
                .label("Spanish")
                .build(),
            try! JWCaptionTrackBuilder()
                .file(URL(string: "http://playertest.longtailvideo.com/caption-files/sintel-ru.srt")!)
                .label("Russian")
                .build()
        ])
        .build(),
    // BIG BUCK BUNNY TRAILER
    try! JWPlayerItemBuilder()
        .mediaId("bbb342")
        .file(URL(string: "http://content.bitsontherun.com/videos/bkaovAYt-52qL9xLP.mp4")!)
        .title("MP4: Big Buck Bunny Trailer")
        .posterImage(URL(string: "http://d3el35u4qe4frz.cloudfront.net/bkaovAYt-480.jpg")!)
        .mediaTracks([
            try! JWCaptionTrackBuilder()
                .file(URL(string: "https://playertest.longtailvideo.com/caption-files/bunny-en.vtt")!)
                .label("English")
                .build(),
            try! JWChapterTrackBuilder()
                .file(URL(string: "http://playertest.longtailvideo.com/assets/os/chapters/bunny-chapters.vtt")!)
                .build()
        ])
        .build(),
    // SINTEL TRAILER
    try! JWPlayerItemBuilder()
        .mediaId("ccc2342")
        .file(URL(string: "http://content.bitsontherun.com/videos/3XnJSIm4-injeKYZS.mp4")!)
        .title("MP4: Sintel Trailer")
        .posterImage(URL(string: "https://vdn.libreflix.org/covers/media/sintel/sintelthumb.jpg")!)
        .build(),
    // ELEPHANT'S DREAM
    try! JWPlayerItemBuilder()
        .mediaId("ddd745")
        .file(URL(string: "http://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/elephantsdream2.smil/playlist.m3u8")!)
        .title("HLS: Elephant's Dream")
        .posterImage(URL(string: "https://www.themoviedb.org/t/p/w250_and_h141_face/6IJ0eK2G8RfBxpULMsIdgzSiHnb.jpg")!)
        .build(),
    // PARADISE
    try! JWPlayerItemBuilder()
        .mediaId("eee342")
        .file(URL(string: "http://playertest.longtailvideo.com/adaptive/paradise/paradise-novtt.m3u8")!)
        .title("HLS: Paradise")
        .build(),
    // CPC DEMO
    try! JWPlayerItemBuilder()
        .mediaId("fff789")
        .file(URL(string: "http://playertest.longtailvideo.com/adaptive/cpcweb/cpcdemo.m3u8")!)
        .title("HLS: CPC Demo")
        .build(),
    // AUDIO ONLY
    try! JWPlayerItemBuilder()
        .mediaId("ggg235r2")
        .file(URL(string: "http://content.bitsontherun.com/videos/kaUXWqTZ-52qL9xLP.mp4")!)
        .title("MP4: Audio Only")
        .posterImage(URL(string: "http://d3el35u4qe4frz.cloudfront.net/kaUXWqTZ-480.jpg")!)
        .build(),
    // SINTEL TRAILER AUDIO ONLY
    try! JWPlayerItemBuilder()
        .mediaId("hhh34t3")
        .file(URL(string: "http://content.bitsontherun.com/videos/3XnJSIm4-I3ZmuSFT.m4a")!)
        .title("M4A: Sintel Trailer (Audio)")
        .posterImage(URL(string: "https://vdn.libreflix.org/covers/media/sintel/sintelthumb.jpg")!)
        .build(),
    // BIP BOP
    try! JWPlayerItemBuilder()
        .mediaId("iii4563")
        .file(URL(string: "http://content.jwplatform.com/videos/aN3S1jGx-B2XWaEP9.mp4")!)
        .title("MP4: Bip Bop")
        .posterImage(URL(string: "http://content.jwplatform.com/thumbs/aN3S1jGx-320.jpg")!)
        .build(),
    // AGENT 327
    try! JWPlayerItemBuilder()
        .mediaId("jjj563")
        .file(URL(string: "http://content.jwplatform.com/videos/4jFmgjZr-B2XWaEP9.mp4")!)
        .title("MP4: Agent 327")
        .posterImage(URL(string: "http://cdn.jwplayer.com/thumbs/4jFmgjZr-720.jpg")!)
        .build(),
]
